HEALTHCARE_COM_SHORT_1 = (
    "There has been general growth in healthcare costs across the different categories."
)
HEALTHCARE_COM_SHORT_2 = (
    "The relative contribution of each category to overall healthcare costs has remained largely the same."
)
HEALTHCARE_COM_SHORT_3 = (
    "The overall rising healthcare costs could significantly affect Singapore's overall cost of living, especially for those with chronic conditions."
)
HEALTHCARE_COM_1 = "We observe a trend of overall growth in healthcare costs, with potential implications for the cost of living. While the various components—hospital services, outpatient services, medicines and health products, and health insurance—have maintained relatively stable proportions over the years, the overall CPI value has experienced fluctuations, with a noticeable upward trajectory from 2020 onwards. This suggests that while the relative distribution of healthcare expenditure across different categories has remained consistent, the overall cost of healthcare has been rising."
HEALTHCARE_COM_2 = "This increased trend in the healthcare CPI could significantly affect Singapore's overall cost of living, especially for people and families with higher healthcare demands or those who depend on particular medications or treatments, as healthcare accounts for a larger amount of monthly spending. While the observed fluctuations in healthcare CPI may appear to average out over time, even temporary increases can significantly impact affordability and strain household budgets. Therefore, the potential impact of these fluctuations on the cost of living should not be underestimated. Concerns over the possibility of further rises in healthcare costs are further raised by the steady upward trajectory that has been observed since 2020."

LIFE_EXPECTANCY_HEALTHCARE_SHORT_1 = "Healthcare costs have steadily risen."
LIFE_EXPECTANCY_HEALTHCARE_SHORT_2 = "Life expectancy has seen fluctuations."
LIFE_EXPECTANCY_HEALTHCARE_SHORT_3 = "In recent years, life expectancy has fallen while healthcare costs continue to rise, questioning spending efficiency."
LIFE_EXPECTANCY_HEALTHCARE_1 = "The dual-axis line graph chart illustrates the relationship between life expectancy and healthcare CPI in Singapore from 2014 to 2023. Life expectancy, while generally on an upward trend, has experienced periods of fluctuation, with a slight dip observed between 2019 and 2021. This suggests that despite advancements in healthcare, various factors can influence life expectancy, such as disease outbreaks, lifestyle changes and access to care."
LIFE_EXPECTANCY_HEALTHCARE_2 = "Meanwhile, healthcare costs have steadily increased over the years, which suggests a growing financial pressure of healthcare in Singapore. This trend can likely be attributed to factors like improvements in medical technology, a greater demand for healthcare services and an aging population. The graph reveals that increases in healthcare costs have not always translated proportionally to gains in life expectancy, raising questions about the efficiency and equity of healthcare spending."
LIFE_EXPECTANCY_HEALTHCARE_3 = "This analysis highlights the need for a deeper analysis of healthcare that considers not only cost but also accessibility, quality of care and preventative measures to ensure a healthy and long-living population. The consistent rise in average healthcare costs throughout the observed period underscores the growing financial burden this sector places on individuals and households. This continuous upward trajectory contributes directly to the overall cost of living, particularly for those with chronic health conditions or limited access to subsidised healthcare."

HEALTHCARE_VS_INCOME_SHORT_1 = "The average income of Singaporeans has seen substantial increases."
HEALTHCARE_VS_INCOME_SHORT_2 = "However, healthcare costs have also been rising."
HEALTHCARE_VS_INCOME_SHORT_3 = "Rising healthcare costs could pose a challenge to the affordability of healthcare despite wage increases."
HEALTHCARE_VS_INCOME_1 = "We observe a slightly concerning trend. The graph clearly illustrates a steady increase in both average income and the healthcare CPI. This simultaneous growth suggests that while Singaporeans' incomes have generally improved, the cost of healthcare services has also been on the rise, which could affect the affordability of healthcare for some residents. However, it is important to acknowledge that solely analysing the healthcare CPI and monthly average wage income in their respective years is insufficient to draw definitive conclusions about the overall affordability of healthcare in Singapore."
HEALTHCARE_VS_INCOME_2 = "Breaking down healthcare costs into specific categories reveals that hospital services and outpatient services consistently constitute the largest proportions of healthcare expenditure. This highlights a potential financial burden associated with inpatient and outpatient care, which can be particularly challenging for individuals and families facing chronic illnesses or unexpected medical emergencies. Moreover, the cost of medicines and health products has also been steadily increasing, adding to the overall healthcare expenditure."
HEALTHCARE_VS_INCOME_3 = "While health insurance can help mitigate some of these costs, its coverage may not fully encompass all healthcare needs, leaving individuals to bear a portion of the expenses. The graph underscores the importance of monitoring healthcare costs and their impact on affordability, particularly for lower-income households."

HEALTHCARE_VS_INCOME_PERCENTAGE_SHORT_1 = (
    "In the previous chart, we looked at the raw numbers for income and healthcare CPI. However, it may be more insightful to analyze the percentage changes in these factors."
)
HEALTHCARE_VS_INCOME_PERCENTAGE_SHORT_2 = (
    "Income usually grew faster than healthcare costs, except in some years."
)
HEALTHCARE_VS_INCOME_PERCENTAGE_SHORT_2 = (
    "Overall, the growth of income has typically surpassed the increase in healthcare expenses."
)
HEALTHCARE_VS_INCOME_PERCENTAGE_1 = "This evaluation of the percentage change in healthcare expenditures against income in Singapore from 2014 to 2024 provides more insight regarding how affordable healthcare is in Singapore. The graph shows that although income and healthcare prices have fluctuated, income has fluctuated at a higher percentage than healthcare expenditures. This implies that salary growth has typically surpassed the increase in healthcare expenses, which may help make healthcare services more affordable for a large number of Singaporeans."
HEALTHCARE_VS_INCOME_PERCENTAGE_2 = "Nonetheless, there have been years, like 2014 and 2023, when healthcare expenses have increased significantly. In certain instances, the percentage change in healthcare expenditures was greater than the change in income, which raises questions about possible affordability issues, particularly for people and families that are dealing with unanticipated medical bills or have limited income growth. Despite these variations, the general pattern indicates that income growth has been comparatively strong when compared to rises in healthcare costs, which may portend well for Singapore's healthcare affordability."

HEALTHCARE_RECO_1 = "Singapore's healthcare system faces the dual challenge of managing rising costs while ensuring equitable access for all citizens. To address this, we recommend that policymakers prioritise an approach that consists of both cost containment and targeted support. This would involve implementing cost-cutting measures such as incentivising preventative care, encouraging cost-effective treatments and improving price transparency."

HEALTHCARE_RECO_2 = "Simultaneously, expanding subsidies, improving access to community-based care and investing in primary healthcare services can help alleviate the financial burden on less fortunate individuals. Exploring novel healthcare financing methods and public health efforts that target lifestyle disorders and promote healthy ageing may also enhance long-term sustainability. Regularly evaluating these measures is vital in ensuring their effectiveness and impact. With this  strategy, Singapore should be able to continue to provide high-quality, affordable and accessible healthcare for all its citizens."
