HYPO_QNS = "To what extent is Singapore's rising cost of living impacting its economic viability for residents?"

INTRO_1 = "The rising cost of living in Singapore is a persistent concern among its citizens, with perceptions of increasing taxes and the costs of necessities, healthcare, and other essential goods and services. Our objective is to investigate whether Singapore is becoming less economically viable, as perceived by many, and to assess the effectiveness of government policies aimed at maintaining a fair and sustainable standard of living."
INTRO_2 = " We hypothesize that the cost of living in Singapore has been rising disproportionately to income growth, potentially creating affordability challenges and impacting the standard of living for certain segments of the population."
INTRO_BULLET_1 = "The cost of necessities, including housing, food, healthcare, and transportation, has been rising according to CPI trends."
INTRO_BULLET_2 = "Healthcare expenditures are exhibiting an upward trend, potentially affecting access to and affordability of healthcare services."
INTRO_BULLET_3 = "While incomes have generally increased, the rate of growth has often felt insufficient to keep pace with the rising cost of living, leading to a sense of financial strain."
INTRO_3 = "To confirm the validity of these hypotheses and provide a more comprehensive understanding of the intricate dynamics affecting Singapore's cost of living, this study will examine these topics in further detail by analyzing a range of economic indicators and policy initiatives."


# conclusion 
CONCLUSION_1 = "In summary, while Singapore has experienced a measurable increase in the cost of living, our analysis demonstrates that the situation is less alarming than commonly perceived. Despite upward trends in the Consumer Price Index (CPI), resident purchasing power has consistently increased, indicating that average income growth has generally outpaced price inflation."
CONCLUSION_2 = "Furthermore, taxation policies, including the Goods and Services Tax (GST), have been implemented with a focus on gradual adjustments, minimizing the impact on affordability. Progressive income and property tax structures ensure that lower and middle-income earners are not disproportionately burdened. While healthcare costs have risen, wage growth has largely kept pace, mitigating affordability concerns for a significant portion of the population."
CONCLUSION_3 = "Therefore, although financial strain remains a valid concern for some residents, the overall economic landscape suggests a successful balancing act between economic growth, social equity, and affordability. Singapore's economic policies and social support systems have demonstrably mitigated the impact of rising costs for the majority of its population, contributing to a relatively stable and sustainable standard of living."
CONCLUSION_4 = "However, it is crucial to acknowledge that averages do not represent the experience of every individual. Ongoing monitoring and targeted policy interventions are essential to address the specific challenges faced by vulnerable segments of the population and to ensure continued economic viability for all residents."