HYPO_QNS = "To what extent is Singapore's rising cost of living impacting its economic viability for residents?"

INTRO_1 = "The rising cost of living in Singapore is a persistent concern among its citizens, with perceptions of increasing taxes and the costs of necessities, healthcare, and other essential goods and services. Our objective is to investigate whether Singapore is becoming less economically viable, as perceived by many, and to assess the effectiveness of government policies aimed at maintaining a fair and sustainable standard of living."
INTRO_2 = " We hypothesize that the cost of living in Singapore has been rising disproportionately to income growth, potentially creating affordability challenges and impacting the standard of living for certain segments of the population."
INTRO_BULLET_HEADING = "Specifically, we aim to answer the following questions:"
INTRO_BULLET_1 = "Have the costs of necessities — including housing, food, healthcare, and transportation — been rising at a rate faster than our income growth?"
INTRO_BULLET_2 = "Are healthcare expenditures exhibiting an upward trend, potentially affecting access to and affordability of healthcare services?"
INTRO_BULLET_3 = "Are Singapore's taxation policies straining the finances of Singaporeans?"
INTRO_BULLET_4 = "How does Singapore's economic situation compare to other countries'?"
INTRO_3 = "To confirm the validity of these hypotheses and provide a more comprehensive understanding of the intricate dynamics affecting Singapore's cost of living, this study will examine these topics in further detail by analyzing a range of economic indicators and policy initiatives."

# Glossary definitions
TERMINOLOGY_INTRO = "Before diving deeper, we introduce some of the key terms we use throughout our analysis for those unfamiliar with the terminology."
GST_DEF = "GST is a tax on consumption that applies to a wide range of products and services. The current GST rate in Singapore is 9% (from 2024 onwards). Its purpose is to generate government money while keeping a minimal tax burden."
GDP_DEF = "The total value of products and services generated by a country per person. It is often used as a measurement of economic output and living standards. A rising GDP per capita indicates economic growth and higher living standards."
CPI_DEF = "The consumer price index (CPI) is a measurement of the average price change over a given period for a basket of products and services. This basket reflects typical household consumption habits and includes categories such as food, clothing, housing, transportation, healthcare, education, and recreation. A rising CPI signals inflation and higher costs of living."
PPP_DEF = "Purchasing power parity (PPP) compares currency values based on a basket of items. As GDP per capita alone can be misleading due to differences in living costs across countries, we use PPP to adjust GDP figures so that they reflect what people can actually afford in their own country, rather than being distorted by exchange rates. Unlike market exchange rates, which fluctuate due to financial factors, PPP focuses on real-world prices."

# conclusion
CONCLUSION_BULLET_HEADING = "While Singapore has experienced a measurable increase in the cost of living, our analysis demonstrates that the situation is less alarming than commonly perceived. Here are what we have understood from the data:"
CONCLUSION_BULLET_1 = "Despite upward trends in the consumer price index (CPI), resident purchasing power has consistently increased, indicating that average income growth has generally outpaced price inflation."
CONCLUSION_BULLET_2 = "Taxation policies, including the goods and services tax (GST), have been implemented with a focus on gradual adjustments, minimizing the impact on affordability. Progressive income and property tax structures have successfully ensured that lower and middle-income earners are not disproportionately burdened."
CONCLUSION_BULLET_3 = "While healthcare costs have risen, wage growth has largely kept pace, mitigating affordability concerns for a significant portion of the population."
CONCLUSION_BULLET_4 = "Compared to other countries, the purchasing power of Singaporeans has not diminished. In fact, it has been growing steadily."
CONCLUSION_CLOSING_1 = "Therefore, although financial strain remains a valid concern for some residents, the overall economic landscape suggests a successful balancing act between economic growth, social equity, and affordability. Singapore's economic policies and social support systems have demonstrably mitigated the impact of rising costs for the majority of its population, contributing to a relatively stable and sustainable standard of living."
CONCLUSION_CLOSING_2 = "However, it is crucial to acknowledge that averages do not represent the experience of every individual. Ongoing monitoring and targeted policy interventions are essential to address the specific challenges faced by vulnerable segments of the population and to ensure continued economic viability for all residents."
