CPI_AGAINST_GST = "There is a general increase in the CPI of necessities over the years, accompanied by a proportional increase in GST rates. It is evident that the rise in CPI correlates directly with the hike in GST, suggesting a strong linkage between the two. The gradual increase in GST beginning around 2017 coincides with an acceleration in the overall CPI. This timing indicates that changes in GST rates are closely linked to fluctuations in consumer prices. While all categories show an increase in CPI, the Food category appears consistently prominent in the CPI stack each year, highlighting its significant and steady contribution to overall consumer expenses."
CPI_AGAINST_GST_Short = (
    "IRAS tax revenue grew, driven by GST, corporate, and property tax increases."
)
TAX_COLLECTED_IRAS = "There is a general rise in the amount of taxes collected by IRAS from 2002 to 2023. Specifically, the components such as Goods and Services Tax (GST), Corporate Income Tax, and Property Tax exhibit substantial increases. Over the years, GST has grown to constitute a significant portion of the revenue, reflecting changes in consumption patterns and possibly tax rate adjustments. Similarly, Corporate Income Tax demonstrates robust growth, likely indicating economic expansion and profitability in the corporate sector. Property Tax also shows a steady rise, which could be attributed to increasing property values and expansions in taxable real estate assets."
TAX_COLLECTED_IRAS_Short = "Singapore's progressive tax system, evident across income and property taxes, aims for fairness by proportionally increasing rates with income and property value"
INCOME_TAX_STEP = "Singapore's Income Tax structure is designed to be progressive, promoting equity and fairness across different income groups. Over the years, the structure has become increasingly segmented, enhancing equity and providing more significant support to lower-income households. Additionally, between 2017 and 2024, further segmentation within the upper tiers of the income hierarchy has been implemented. These efforts have been made to better accommodate higher-income groups as well."
INCOME_TAX_STEP_Short = "Singapore's progressive income tax system has evolved with increased segmentation to boost equity by supporting lower-income households while fine-tuning brackets for higher earners."
INCOME_TAX_HEATMAP = "The heat map uses varying shades to represent the different percentages of income paid in taxes by various income groups, clearly illustrating Singapore's progressive income tax structure.  It depicts a proportional relationship between income tax and household income. The color gradient, transitioning from darker blue for lower income taxes to yellow for higher income taxes, effectively demonstrates how tax rates increase proportionally with household income. This visual gradient underscores the principle that higher earners pay a more significant percentage of their income in taxes, reflecting the system's aim to promote fairness and financial equity."
INCOME_TAX_HEATMAP_Short = (
    "Singapore uses progressive income tax, increasing rates with income."
)
PROPERTY_TAX_ANNUAL = "Singapore's property tax rates are structured to be progressive, as depicted in the graphs showing tax rates by annual value range for owner-occupied residential properties. The diagrams illustrate a clear trend where the tax rate increases with the annual value of the property, emphasising the principle of equity within the tax system. For properties with lower annual values, the tax rates are considerably lower, represented by the bottom of the ladder. As the property value increases, tax rates escalate, transitioning through the ladder of progressiveness to the summit for the highest property values."
PROPERTY_TAX_ANNUAL_Short = "Singapore's progressive property tax increases with annual value, ensuring higher-value properties pay more, reflecting equity."
PROPERTY_TAX_ANNUAL_HDB = "The Property Tax against Annual Value and HDB types graphs display the progressive nature of property tax collection in Singapore across different Housing and Development Board (HDB) types from 2014 to 2023. It correlates the property tax collected with the median annual value of HDB properties, ranging from 1 or 2-room units to executive and other types. The data points are color-coded by HDB type, illustrating that higher-value properties, such as executive units, consistently incur higher tax rates, as seen by their positioning towards the higher end of the annual value spectrum. This setup underlines the fairness embedded in Singapore’s tax system, where tax obligations increase with property value. Over the years, there is an evident shift in tax collection patterns with an increase in the proportion of taxes collected from higher-value properties, reflecting adjustments to ensure equity as market conditions evolve. The progressive tax rates are designed to burden less the lower-income homeowners, shown by the lower tax rates associated with smaller HDB types like 1 or 2-room units, demonstrating the government’s commitment to social equity."
PROPERTY_TAX_ANNUAL_HDB_Short = "Singapore's property tax data (2014–2023) show that higher-value HDB properties incur higher taxes, affirming a progressive system."
TAX_RECO = "We recommend maintaining the Goods and Services Tax (GST) at a low and stable rate. While the gradual increase in GST over the years may affect Singaporean residents, we recognize that this slight growth is necessary for the country's continued economic development. However, it is crucial that GST rates are carefully monitored to ensure stability. Additionally, the progressive structure of Singapore’s income and property taxes has significantly promoted equity among different income groups. We strongly advise continuing on this path. Introducing further segregation within the lower and middle-income brackets could enhance equity even more. Overall, we believe that the Singaporean government is moving in the right direction concerning tax management, effectively balancing growth needs with social fairness."
