TAX_COLLECTED_IRAS_SHORT_BULLET_1 = "As a preliminary context, we look at the tax collected by the Inland Revenue Authority of Singapore (IRAS)."
TAX_COLLECTED_IRAS_SHORT_BULLET_2 = (
    "The tax collected by the IRAS has generally been increasing."
)
TAX_COLLECTED_IRAS_SHORT_BULLET_3 = "Revenue from goods and services tax (GST), corporate income tax and property tax have seen relatively large rises."
TAX_COLLECTED_IRAS_SHORT_BULLET_4 = "However, the tax collected alone does not tell us much — we must compare these numbers to the income of Singaporeans and Singapore's CPI."
TAX_COLLECTED_IRAS = "There is a general rise in the amount of taxes collected by IRAS from 2002 to 2023. Specifically, the components such as the goods and services tax (GST), corporate income tax, and property tax exhibit substantial increases. Over the years, GST has grown to constitute a significant portion of the revenue, reflecting changes in consumption patterns and possibly tax rate adjustments. Similarly, corporate income tax demonstrates robust growth, likely indicating economic expansion and profitability in the corporate sector. Property tax also shows a steady rise, which could be attributed to increasing property values and expansions in taxable real estate assets."

CPI_VS_GST_SHORT_BULLET_1 = "The CPI of necessities has generally increased."
CPI_VS_GST_SHORT_BULLET_2 = (
    "The GST rate has also increased several times over the years."
)
CPI_VS_GST_SHORT_BULLET_3 = (
    "However, there does not seem to be a clear link between the GST rate and CPI."
)
CPI_VS_GST_1 = "The GST rate increased from 3% in 2003 to 5% in 2004, then to 7% in 2007, and is progressively increasing to 9% by 2023. It has undergone significant changes over the years, reflecting the nation's evolving revenue needs and economic priorities. A popular notion is that increases in the GST instantly translate into increases in the CPI as businesses pass on the additional costs to customers.  However, the link appears to be more complex."
CPI_VS_GST_2 = "Regardless of GST reforms, the CPI has been steadily rising.  Notably, the recent GST hike from 8% to 9% has not yet resulted in a commensurate CPI increase, indicating that firms are now absorbing the higher tax burden. This could be the result of competitive pressures, delayed pricing increases, existing profit margins, economic conditions or regulatory effects. While the immediate impact on consumers appears to be low, the long-term repercussions remain to be determined. Continuous CPI monitoring is required to assess whether this absorption continues or if prices progressively adapt to higher GST."

INCOME_TAX_STEP_SHORT_BULLET_1 = "Before analyzing income tax further, we should first understand Singapore's income tax structure."
INCOME_TAX_STEP_SHORT_BULLET_2 = "Singapore uses a progressive income tax system, which has evolved with increased segmentation to boost equity."
INCOME_TAX_STEP_SHORT_BULLET_3 = "The income tax system supports lower-income households while fine-tuning brackets for higher earners."
INCOME_TAX_STEP_SHORT_BULLET_4 = "Income tax rates have not changed for lower-income groups, but have seen general increases for those with higher incomes."
INCOME_TAX_STEP = "Singapore's income tax structure is evidently designed to be progressive, promoting equity and fairness across different income groups. Over the years, the structure has become increasingly segmented, enhancing equity and providing more significant support to lower-income households. Additionally, between 2017 and 2024, further segmentation within the upper tiers of the income hierarchy has been implemented. These efforts have been made to better accommodate higher-income groups as well."

INCOME_TAX_HEATMAP_SHORT_BULLET_1 = "To understand Singapore's income taxation further, we must compare the income tax rates with the income of Singaporeans."
INCOME_TAX_HEATMAP_SHORT_BULLET_2 = "In the heatmap, a darker blue means a smaller percentage of assessed income was paid in taxes. Conversely, a brighter yellow indicates a higher percentage."
INCOME_TAX_HEATMAP_SHORT_BULLET_3 = "Singapore's income tax structure appears to have successfully promoted equity. Lower-income earners contribute a smaller percentage of their income to taxes, while higher-income earners contribute a higher percentage."
INCOME_TAX_HEATMAP_1 = "The progressive nature of Singapore's income tax system is evident in the data from 2014 to 2023, which reveals a clear disparity in income tax rates across varying income levels. Singaporeans with higher incomes have consistently been contributing a higher percentage of their assessed income to income taxes, relative to those with lower incomes.  It appears that Singapore’s progressive tax structure does successfully distribute the tax burden more equitably to ensure those with greater financial capacity contribute a proportionally larger share."
INCOME_TAX_HEATMAP_2 = "While the overall trend highlights this disparity, it is worth noting that the exact percentage of income paid in taxes varies across income groups and years. For instance, those earning above 1,000,001 SGD consistently pay the highest percentage, exceeding 20% in most years. In contrast, those earning between 20,000 and 30,000 SGD pay a significantly lower percentage, often below 5%. This approach to taxation reflects the government's efforts to balance revenue generation with social equity considerations."

PROPERTY_TAX_ANNUAL_SHORT_BULLET_1 = "Before analyzing income property further, we should first understand Singapore's property tax structure."
PROPERTY_TAX_ANNUAL_SHORT_BULLET_2 = "Property tax rates are gradually increasing."
PROPERTY_TAX_ANNUAL_SHORT_BULLET_3 = "Rising property tax rates could lead to increased housing and operational expenses, which may reduce the purchasing power of Singaporeans."
PROPERTY_TAX_ANNUAL_1 = "A gradual upward trend in overall tax rates is evident. Notably, the changes effective from 2024 onwards indicate a significant adjustment, with the introduction of new tiers and revised tax rates, potentially aimed at capturing increased property values and contributing to public finances."
PROPERTY_TAX_ANNUAL_2 = "From a cost of living perspective, rising property taxes directly impact homeowners and businesses, leading to increased housing and operational expenses. These costs would reduce the purchasing power of Singaporean residents and may also then cascade down to consumers through higher prices for goods and services, potentially fuelling inflationary pressures. Consequently, while property tax is crucial for government revenue and potentially moderating speculative property investments, its consistent upward trajectory directly and indirectly affects the cost of living in Singapore, particularly concerning housing affordability and business operational costs."

PROPERTY_TAX_ANNUAL_HDB_SHORT_BULLET_1 = "Larger apartment types (e.g., maisonettes and five-room flats) generally have higher property tax collections than smaller ones."
PROPERTY_TAX_ANNUAL_HDB_SHORT_BULLET_2 = "Higher taxation on larger flat types is sensible as the affordability of a flat is influenced by the salary of its residents."
PROPERTY_TAX_ANNUAL_HDB_SHORT_BULLET_3 = "However, taxation on smaller flat types has also been increasing, which could place a financial burden on Singaporeans."
PROPERTY_TAX_ANNUAL_HDB_1 = "Property tax collection in the charts above shows trends across different Housing and Development Board (HDB) flat types in Singapore, revealing varying impacts on the cost of living. For each type of flat, the graphs show tax collection against annual value. Larger apartment types, such as executive maisonettes and five-room apartments, typically have higher property tax collections, which is indicative of their higher yearly values and, hence, higher taxation."
PROPERTY_TAX_ANNUAL_HDB_2 = "As the affordability of a flat is based on the salary its residents obtain, higher taxation of the individuals residing within the upper echelons of the financial hierarchy is sensible and reasonable. The rising trajectory of tax collected for the majority of flat types indicates a progressive increase in the burden of property taxes over time. This increasing trend suggests that household finances will be further impacted, especially for those who own larger apartments. Despite paying lower absolute tax amounts, the data indicates that owners of smaller apartments, such as three- and four-room apartments, are also facing rising property tax loads, which may be proportionately more substantial in relation to their income levels. In conclusion, trends in property taxes for all HDB apartment types show that homeowners' costs are rising, hence putting more financial strain on Singaporeans."

TAX_RECO_GST = "To mitigate the impact of rising GST, our recommendation is for policymakers to consider expanding the GST Voucher Scheme and introduce targeted exemptions or reduced rates for essential goods and services. Apart from that, continuous monitoring of GST's impact on household budgets, particularly for lower- and middle-income earners, can be employed. Additionally, regular reviews of the GST system can ensure its continued effectiveness, fairness, and alignment with broader economic and social objectives. These measures would help to ensure that the GST system remains equitable and sustainable, contributing to a stable and inclusive economy for all Singaporeans."

TAX_RECO_INCOME_TAX = "To maintain an equitable and sustainable income tax system in Singapore, our recommendation is for policymakers to prioritise a balanced approach that considers both revenue generation and the financial well-being of all income groups. We believe that maintaining a progressive tax structure is crucial for social redistribution, but regular reviews and adjustments to income tax brackets and rates are necessary to account for economic changes and alleviate the burden on lower- and middle-income earners. Investigating targeted tax breaks or refunds can further enhance fairness. Additionally, we feel that increased transparency regarding the use of tax revenue can foster public trust and understanding. Implementing these recommendations should promote a tax system that is both fair and efficient, supporting a stable and inclusive economy for all Singaporeans."

TAX_RECO_PROPERTY_TAX = "We recommend that policymakers prioritise implementing a multifaceted approach. This involves refining annual value bands and tax rates to provide relief for lower-income households and those living in smaller HDB flats, expanding public housing options and enhancing first-time buyer programmes.  Additionally, increasing transparency regarding property tax adjustments and revenue allocation would foster public trust. Monitoring market dynamics and evaluating programme effectiveness would allow policymakers to further ensure that housing policies remain sustainable and inclusive, promoting a stable and equitable society where all residents have access to safe and affordable housing."
