[project]
name = "ict305-project-dashboard"
version = "0.1.0"
description = "An investigation of the economic viability of living in Singapore"

[tool.uv]
package = false

[tool.uv.sources]
ict305-project-parser = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]
